version: '2'
services:
  projectmanager-app:
    image: projectmanager
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://projectmanager-postgresql:5432/projectManager
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  projectmanager-postgresql:
    extends:
      file: postgresql.yml
      service: projectmanager-postgresql
